### ISSUE TITLE
Cannot build PCL

### ISSUE THREAD

**Issue by weitzhandler** [Fody/PropertyChanging#10]
Hi,

I'm trying to use PropertyChanging.Fody in my Xamarin PCL app (Profile 44: UWP, Droid, iOS). 
I get this error on build:

>Fody: An unhandled exception occurred:
Exception:
Sequence contains no matching element
StackTrace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModuleWeaver.ExecuteWinRT() in C:\projects\propertychanging\PropertyChanging.Fody\MsCoreReferenceFinder.cs:line 128
   at ModuleWeaver.FindCoreReferences() in C:\projects\propertychanging\PropertyChanging.Fody\MsCoreReferenceFinder.cs:line 29
   at ModuleWeaver.Execute() in C:\projects\propertychanging\PropertyChanging.Fody\ModuleWeaver.cs:line 23
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 83
Source:
System.Core
TargetSite:
TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])	Hatzoloh.App			

Weavers file looks like this:

    <Weavers>
      <PropertyChanged/>
      <PropertyChanging/>
    </Weavers>

Xamarin PCL, doesn't provide the `INotifyPropertyChanging` interface which I included in my library (it does have the event handler delegate and the PropertyChangingEventArgs). Is that the reason it doesn't build?
I'm not so sure how Fody verifies and injects the interfaces, but is it possible to emit those interfaces as they are without type matching?

**Comment by SimonCropp** [comment]
"is it possible to emit those interfaces as they are without type matching" TBH i dont know. have you tried?

**Comment by weitzhandler** [comment]
@SimonCropp I don't IL at all.
Do you recognize the error?
I'm really a Fody internals noob, my question is if Fody verifies what `INotifyPropertyChanging` actually is, where does it lookup this type. Can it be in my assembly or it must be the system's. What's the source of the error?

**Comment by SimonCropp** [comment]
well the error is here https://github.com/Fody/PropertyChanging/blob/master/PropertyChanging.Fody/MsCoreReferenceFinder.cs#L128

so your guess about missing INotifyPropertyChanging is correct. the problem is, afaik, u need to know the assembly a type exists in to add a ref to it. so i dont see a way around this

**Comment by weitzhandler** [comment]
Can the assembly be the processed assembly? Can you add it to the search or it doesn't work this way?

**Comment by SimonCropp** [comment]
> Xamarin PCL, doesn't provide the INotifyPropertyChanging interface which I included in my library (it does have the event handler delegate and the PropertyChangingEventArgs). 

can u explain why

**Comment by weitzhandler** [comment]
Unfortunately, Xamarin didn't include the `INotifyPropertyChanging` interface in their PCL. So I just want to write this class by hand in my app and have fody's `INotifyPropertyChanging` declarations refer to it.

![image](https://cloud.githubusercontent.com/assets/2716316/26430096/bc77ff5e-40f3-11e7-8706-92444eabc6cb.png)

**Comment by SimonCropp** [comment]
as u guessed, currently using a custom INotifyPropertyChanging is not supported. I would accept a PR for it though

**Comment by weitzhandler** [comment]
I don't how to hi in IL...

**Comment by SimonCropp** [comment]
then it is a good time to learn. start by adding a failing unit test, then debug into it to understand how the code flows

**Comment by weitzhandler** [comment]
haha i need to find time lol... thank u so much for all!

**Comment by SimonCropp** [comment]
Do u think u will get to this? Or should we close?

**Comment by weitzhandler** [comment]
I'm sorry but I won't be able in the near future.

**Comment by SimonCropp** [comment]
Sorry to hear

**Comment by SimonCropp** [comment]
Btw u say this problem is in xamarin pcls. Given pcls are deprecated, does the same problem exist in xamarin for netstandard?

**Comment by weitzhandler** [comment]
First of all, thanks for your sympathy.
Besides, since `INotifyPropertyChanging` is in netstandard, shouldn't be an issue.

**Comment by SimonCropp** [comment]
Ok cool. Ping back if u have any issues with net standard
