### ISSUE TITLE
System.InvalidProgramException: 'Common Language Runtime detected an invalid program.

### ISSUE THREAD

**Issue by OlegNadymov** [Fody/PropertyChanging#156]
I got a bug "System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'" after moving from .Net Framework 4.7.2 to .Net Core 3.1.
The demo:
```C#
private class SampleClass :
    INotifyPropertyChanged,
    INotifyPropertyChanging
{

    public event PropertyChangedEventHandler PropertyChanged;
    public event PropertyChangingEventHandler PropertyChanging;

    private bool? _isFlag;

    //[PropertyChanged.DoNotNotify]
    //[PropertyChanging.DoNotNotify]
    public bool IsFlag
    {
        get { return _isFlag ?? (_isFlag = this.GetFlag()).Value; }
        set { _isFlag = value; }
    }


    private bool GetFlag()
    {
        return false;
    }
}

public void FodyOnPropertyChangingNullableFieldPlusMethodInGetter()
{
    // Arrange
    var wasFired = false;
    var obj = new SampleClass();
    obj.PropertyChanging += (object sender, PropertyChangingEventArgs e) => wasFired = true;
    Exception exc = null;

    // Act
    try
    {
        obj.IsFlag = true;
    }
    catch (Exception e)
    {
        exc = e; //here "System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'"
    }
}
```
This example works on .Net Framework 4.7.2, but does not work on .Net Core 3.1.

Fody v.6.1.1
PropertyChanging.Fody v.1.30.0
PropertyChanged.Fody v.3.2.7
Visual Studio 2019

**Comment by ltrzesniewski** [comment]
Thanks! At first glance, it looks like the problem is caused by the injected equality check:

```
      IL_0000: ldarg.0      // this
      IL_0001: ldfld        valuetype [mscorlib]System.Nullable`1<bool> ConsoleApp1.Program/SampleClass::_isFlag
      IL_0006: ldarg.1      // 'value'
      IL_0007: call         bool [mscorlib]System.Nullable::Equals<bool>(valuetype [mscorlib]System.Nullable`1<!!0/*bool*/>, valuetype [mscorlib]System.Nullable`1<!!0/*bool*/>)
      IL_000c: brfalse.s    IL_0010
```

It passes a `bool` value to a method with a `bool?` parameter type. The error also happens when th `PropertyChanged` weaver is removed.

**Comment by OlegNadymov** [comment]
Glad to help! It's interesting because example works perfect on .Net Framework but not on .Net Core.

**Comment by ltrzesniewski** [comment]
I also tried it quickly on net48, and it failed for me. Also, note that the equality check logic seems wrong - it should be calling the `IsFlag` getter instead of trying to do something with the `_isFlag` field.

**Comment by OlegNadymov** [comment]
I changed target in my project from net472 to net48. And it also worked. But there is more interesting situation: I downgraded .Net Core from 3.1 to 2.2 and it also started working. Then I checked .Net Core 3.0 and it does not work. The problem seems to be reproducing on .Net Core starting with 3.0.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by OlegNadymov** [comment]
@ltrzesniewski @SimonCropp thanks! 👍
