### ISSUE TITLE
Update to Netstandard 2.0

### ISSUE THREAD

**Issue by FutureTD** [Fody/PropertyChanging#282]
Was wondering if this library could be updated to Netstandard 2.0 as you recently did for the other libraries, Which was appreciated by the way.

**Comment by ltrzesniewski** [comment]
Sure 🙂 

@SimonCropp I noticed you added .NET Standard 2.0 _and_ 2.1 targets in many weavers, but I don't think that adding a 2.1 target is useful if 2.0 is already included, it will just increase the package size.

**Comment by SimonCropp** [comment]
ok. i will remove the 2.1.

**Comment by ltrzesniewski** [comment]
I released v1.30.2 @FutureTD

**Comment by SimonCropp** [comment]
>  it will just increase the package size.

actually i dont think this matters. it will only be the lib part. so 2-4kb

**Comment by ltrzesniewski** [comment]
Yes, it was just a way to say that the 2.1 target is not useful if it does exactly the same thing as 2.0.
